"""empty message

Revision ID: 64c01e59b076
Revises: a1098d075679
Create Date: 2020-02-23 14:05:23.086336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c01e59b076'
down_revision = 'a1098d075679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('gender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'gender')
    # ### end Alembic commands ###
