"""empty message

Revision ID: a1098d075679
Revises: 
Create Date: 2020-02-23 14:02:25.654381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1098d075679'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
